server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bankcard}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    url: /docs/openapi.yaml
    enabled: true

logging:
  level:
    com.bankcard: DEBUG
    org.springframework.security: INFO
    org.hibernate.orm.jdbc.bind: TRACE

app:
  encryption:
    secret-key: ${ENCRYPTION_KEY}

  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
