server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bankcard}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    com.bankcard: DEBUG
    org.springframework.security: INFO

app:
  encryption:
    secret-key: ${ENCRYPTION_KEY}

  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
